<a href="https://colab.research.google.com/github/babatundeibukun/DEEP-LEARNING-PROJECT---COMPUTER/blob/main/solving_data_imbalance_with_smote_method.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
df  = pd.read_csv('/content/Churn_Modelling.csv')
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
df.shape

(10000, 14)

In [6]:
df.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [7]:
#I need to drop the columns that are not needed

df1 = df.drop(['RowNumber', 'CustomerId', 'Surname'], axis = 1 )
df1.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [8]:
df1.dtypes

CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [9]:
df1['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [10]:
df1['Gender'] = df1['Gender'].replace({'Female' : 0, 'Male' : 1})

<ipython-input-10-5ed6f3f3a3eb>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df1['Gender'] = df1['Gender'].replace({'Female' : 0, 'Male' : 1})

In [11]:
df1 = pd.get_dummies(df1, 'Geography', drop_first = True, dtype= int)
df1.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,0,0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0,1
2,502,0,42,8,159660.80,3,1,0,113931.57,1,0,0
3,699,0,39,1,0.00,2,0,0,93826.63,0,0,0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0,1

#Realized that I need some scaling

In [12]:
from sklearn.preprocessing import MinMaxScaler
sx = MinMaxScaler()


cols_to_scale = ['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'EstimatedSalary']

df1[cols_to_scale] = sx.fit_transform(df[cols_to_scale])

df1[cols_to_scale].head()

   CreditScore       Age  Tenure   Balance  NumOfProducts  EstimatedSalary
0        0.538  0.324324     0.2  0.000000       0.000000         0.506735
1        0.516  0.310811     0.1  0.334031       0.000000         0.562709
2        0.304  0.324324     0.8  0.636357       0.666667         0.569654
3        0.698  0.283784     0.1  0.000000       0.333333         0.469120
4        1.000  0.337838     0.2  0.500246       0.000000         0.395400

In [13]:
df1.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain
0,0.538,0,0.324324,0.2,0.000000,0.000000,1,1,0.506735,1,0,0
1,0.516,0,0.310811,0.1,0.334031,0.000000,0,1,0.562709,0,0,1
2,0.304,0,0.324324,0.8,0.636357,0.666667,1,0,0.569654,1,0,0
3,0.698,0,0.283784,0.1,0.000000,0.333333,0,0,0.469120,0,0,0
4,1.000,0,0.337838,0.2,0.500246,0.000000,1,1,0.395400,0,0,1

#Checking if there is an imbalance in the outcome

In [14]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [ ]:
#There is huge imbalance in the dataset, I can solve that with oversampling the minority class, undersampling the majority class, smote or ensemble orr focal loss,
# So i will try all of them one after the other but starting wiht smote since i did undersampling the majority class already .

In [16]:
X = df1.drop('Exited', axis = 1)
X.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_Germany,Geography_Spain
0,0.538,0,0.324324,0.2,0.000000,0.000000,1,1,0.506735,0,0
1,0.516,0,0.310811,0.1,0.334031,0.000000,0,1,0.562709,0,1
2,0.304,0,0.324324,0.8,0.636357,0.666667,1,0,0.569654,0,0
3,0.698,0,0.283784,0.1,0.000000,0.333333,0,0,0.469120,0,0
4,1.000,0,0.337838,0.2,0.500246,0.000000,1,1,0.395400,0,1

In [18]:
y = df1['Exited']

#SMOTE - METHOD

In [15]:
#first i need to divide the data set into train and test split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split( X, y , test_size = 0.2 , random_state = 1234, stratify = y)

NameError: name 'X' is not defined

In [ ]:
X_